# Generated by Django 4.0.3 on 2022-05-15 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlcuentas', '0002_account_acc_fkuser_assignments_assi_fkuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assi_datepurchase',
            field=models.DateField(verbose_name='Dia De La Compra'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assi_daterenovation',
            field=models.DateField(verbose_name='Dia De La Renovación'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assi_fkaccount',
            field=models.ForeignKey(db_column='assi_fkaccount', on_delete=django.db.models.deletion.DO_NOTHING, to='controlcuentas.account', verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assi_fkclient',
            field=models.ForeignKey(db_column='assi_fkclient', on_delete=django.db.models.deletion.DO_NOTHING, to='controlcuentas.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assi_note',
            field=models.TextField(verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assi_profile',
            field=models.CharField(max_length=25, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assi_purchaseprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio De La Compra'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assi_sellingprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de la venta'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assi_status',
            field=models.IntegerField(blank=True, db_column='assI_status', null=True, verbose_name='Estatus'),
        ),
    ]
