# Generated by Django 4.0.3 on 2022-05-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlcuentas', '0003_alter_assignments_assi_datepurchase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cli_fkuser',
            new_name='cli_fkuser_id',
        ),
    ]
