# Generated by Django 4.0.3 on 2022-05-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlcuentas', '0004_rename_cli_fkuser_client_cli_fkuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cli_fkuser_id',
            new_name='cli_fkuser',
        ),
    ]
