# Generated by Django 4.0.3 on 2022-05-25 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controlcuentas', '0005_rename_cli_fkuser_id_client_cli_fkuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_fkuser',
            field=models.ForeignKey(db_column='acc_fkuser', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assi_fkuser',
            field=models.ForeignKey(db_column='acc_fkuser', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='cli_fkuser',
            field=models.ForeignKey(db_column='acc_fkuser', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
