# Generated by Django 4.0.3 on 2022-05-25 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controlcuentas', '0006_alter_account_acc_fkuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assi_fkuser',
            field=models.ForeignKey(db_column='assi_fkuser', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='cli_fkuser',
            field=models.ForeignKey(db_column='cli_fkuser', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
