# Generated by Django 4.0.3 on 2022-05-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcuentas', '0007_alter_assignments_assi_fkuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assi_status',
            field=models.IntegerField(blank=True, db_column='assi_status', null=True, verbose_name='Estatus'),
        ),
    ]
