# Generated by Django 4.0.3 on 2022-05-28 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controlcuentas', '0008_alter_assignments_assi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_email',
            field=models.CharField(max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_fktypeaccount',
            field=models.ForeignKey(db_column='acc_fktypeaccount', on_delete=django.db.models.deletion.DO_NOTHING, to='controlcuentas.cattypeaccount', verbose_name='Tipo De Cuenta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_fkuser',
            field=models.ForeignKey(db_column='acc_fkuser', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_note',
            field=models.TextField(verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_password',
            field=models.CharField(max_length=100, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_status',
            field=models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], verbose_name='Estatus'),
        ),
    ]
